### ISSUE TITLE
Breaks in Yii 2.0.11.1

### ISSUE THREAD

**Issue by garancsi** [thrieu/yii2-grid-view-state#1]
In Yii 2.0.11.1 they implemented the EVENT_INIT const in Widget class.
Implementing the FilterStateInterface in custom GridView class overwrites the Widget class const, resulting in a compile error: 
Cannot inherit previously-inherited or override constant EVENT_INIT from interface thrieu\grid\FilterStateInterface

**Comment by asaarashi** [comment]
For backward compability, do you think changing `EVENT_INIT`'s name to another one is a good solution?
 You could submit a pull request.

**Comment by giovaz94** [comment]
If you are tracking the EVENT_INIT of the Widget you could use the Widget::EVENT_INIT directly. 
You can't declare another time a constant with the same name from the Interface.
