### ISSUE TITLE
Please register package in packagist.org

### ISSUE THREAD

**Issue by uldisn** [thrieu/yii2-grid-view-state#2]

**Comment by newerton** [comment]
Problem 1
- The requested package thrieu/yii2-grid-view-state could not be found in any version, there may be a typo in the package name.

**Comment by asaarashi** [comment]
Sorry, I didn't notice
You could check it via

[https://packagist.org/packages/thrieu/yii2-grid-view-state](https://packagist.org/packages/thrieu/yii2-grid-view-state)
