### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by nye** [thrieu/yii2-grid-view-state#7]
Hello,

I've just followed the 3 steps to make my gridview remember filters but I can't manage to make it work at all. There are no errors, just not remembering filters...

Any idea on what could be? Am I doing something wrong?

I'm using Yii 2.0.15.1

Thanks in advance

**Comment by nye** [comment]
I'm trying to find why is not working and what I found so far is that in [FilterStateBehavior.php at line 49](https://github.com/thrieu/yii2-grid-view-state/blob/e53e89d311c61ddef2f5f6b7cde1d0d6bd1ae145/FilterStateBehavior.php#L49) is looping all columns checking if they are of class `DataColumn`, which they don't, because `$gridView->columns` return a plain array instead of an array of objects...

So, it is always ignoring all column filters.

**Comment by nye** [comment]
I've tried adding creating the column object and then it works. Something like this:

```
$column = Yii::createObject(array_merge([
    'class' => DataColumn::className(),
    'grid' => $gridView,
, $column));
```
Is there a reason why `$gridView->columns` is returning a plain array instead of `Column` objects?

**Comment by tranch** [comment]
@nye Please show your context code.

**Comment by nye** [comment]
First I extended the GridView class as instructed.

Then in my view i show a GridView like this:

```
$model = new ProductSearch();

...

echo GridView::widget([
	'id'=>$this->context->id.'-grid',
	'dataProvider' => $model->search(),
	'filterModel' => $model,
	'as filterBehavior' => \thrieu\grid\FilterStateBehavior::className(),
	'columns' => [
	  [
		'attribute' => 'content.name',
		'value' => function($data){ return Html::a($data->content->name, ['update', 'id'=>$data->id]); },
	  	'format' => 'raw',
	  	'contentOptions' => ['width' => '40%']
	  ],

	  ...
	  ...

	  ['class' => 'backend\components\ActionColumn']
	]
]);
```

and in ProductSearch class:

```
class ProductSearch extends \common\models\Product{
	public function search(){
		$query = self::find();

		$dataProvider = new \yii\data\ActiveDataProvider([
			'query' => $query,
		        'pagination' => [
		        'params' => GridView::getMergedFilterStateParams(),
		],
		'sort' => [
			'params' => GridView::getMergedFilterStateParams(),
		]]);

		$query->joinWith(['content AS product_content']);

		$dataProvider->sort->attributes['content.name'] = [
			'asc' => ['product_content.name' => SORT_ASC],
			'desc' => ['product_content.name' => SORT_DESC],
		];
		
		// load the search form data and validate
		if(!($this->load(GridView::getMergedFilterStateParams()) && $this->validate())){
			return $dataProvider;
		}

		$query->andFilterWhere(['id' => $this->id])
			->andFilterWhere(['status' => $this->status])
			->andFilterWhere(['featured' => $this->featured])
			->andFilterWhere(['like', 'product_content.name', $this->getAttribute('content.name')]);

		return $dataProvider;
	}
}
```

**Comment by tranch** [comment]
@nye I tried the code, and I think the problem is: at the bottom of `ProductSearch`, in the `andFilterWhere` mehtod, you should assign a property directly, instead of call from `getAttribute()`.

you can declare a property i.e. `contentName` in the search model, and use it as the column's attribute in GridView, or set `filter` option to `false`.
